### ISSUE TITLE
Update docs/examples to have gateway intents

### ISSUE THREAD

**Issue by deadshot465** [simmsb/racket-cord#9]
Following the example here: [https://docs.racket-lang.org/racket-cord/index.html](https://docs.racket-lang.org/racket-cord/index.html), the console got stuck at
```bash
[debug] discord: IDENTIFYING
[debug] discord: Starting to heartbeat at a period of 165/4 sec
[debug] discord: DISPATCHING EVENT: READY
```
after starting. Did I miss something or is it a known bug?

**Comment by williewillus** [comment]
You need to declare gateway intents. The library doesn't declare any by default (though maybe it should)

**Comment by goderich** [comment]
@williewillus what are gateway intents, and how to declare them properly?

If the documentation could provide a minimal working example, that would be great. I'd much rather write a bot in Racket than Python :)

**Comment by williewillus** [comment]
https://discord.com/developers/docs/topics/gateway#gateway-intents

**Comment by williewillus** [comment]
updated
